name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: |
          npm -g i yarn

      - name: Install dependencies
        run: yarn

      - name: Run linter and tests
        run: yarn test

      - name: Build
        run: yarn build

        env:
          CI: true
